// 自動產生:案例素材資料模型(來源:Sales Kit p24–p53 實際產品/網站畫面,經裁切去簡報框)
// 欄位:slug/name/industry/type/url/sourcePage/mediaType/focalPoint/cover{src,fallback,w,h,alt}/thumbnail/gallery[]
// i18n(Phase 1):name/industry/type/d/alt 走 t(zh,en);slug 是識別鍵不翻。
// 名稱英譯與 content.js 既有英譯逐字一致(單一翻譯來源)。
import { t } from './i18n.js';
export const FEATURED_MEDIA = [
 { slug: 'wedding', name: t('婚禮產業 AI 大禮包', 'Wedding Industry AI Suite'), industry: t('婚禮婚慶', 'Weddings'), type: t('AI 系統', 'AI system'), sourcePage: 'p24', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: '/assets/cases/wedding.webp', fallback: '/assets/works/work-wedding.png', w: 1100, h: 490, alt: t('婚禮產業 AI 大禮包系統畫面:婚紗試穿模擬、社群發文中心與客戶續談 CRM', 'Wedding Industry AI Suite: dress try-on previews, social publishing hub and follow-up CRM') },
   thumbnail: { src: '/assets/cases/wedding.webp', w: 1100, h: 490 },
   gallery: [
     { src: '/assets/cases/wedding.webp', fallback: '/assets/works/work-wedding.png', w: 1100, h: 490, alt: t('婚禮產業 AI 大禮包系統畫面:婚紗試穿模擬、社群發文中心與客戶續談 CRM', 'Wedding Industry AI Suite: dress try-on previews, social publishing hub and follow-up CRM') },
     { src: '/assets/cases/wedding-g1.webp', fallback: '/assets/works/work-wedding.png', w: 820, h: 869, alt: t('婚禮產業 AI 大禮包——婚紗試穿與試妝模擬介面', 'Wedding Industry AI Suite — dress try-on and makeup preview UI') },
     { src: '/assets/cases/wedding-g2.webp', fallback: '/assets/works/work-wedding.png', w: 820, h: 747, alt: t('婚禮產業 AI 大禮包——社群影片與發文中心介面', 'Wedding Industry AI Suite — social video and publishing hub UI') },
     { src: '/assets/cases/wedding-g3.webp', fallback: '/assets/works/work-wedding.png', w: 820, h: 869, alt: t('婚禮產業 AI 大禮包——客戶續談 CRM 與名單畫面', 'Wedding Industry AI Suite — follow-up CRM and lead list') }
 ] },
 { slug: 'interior', name: t('室內設計 AI 整合平台', 'Interior Design AI Platform'), industry: t('室內設計裝修', 'Interior design'), type: t('AI 系統', 'AI system'), sourcePage: 'p25', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: '/assets/cases/interior.webp', fallback: '/assets/works/work-interior.png', w: 1100, h: 490, alt: t('室內設計 AI 整合平台畫面:空間渲染、風格模擬與自動提案簡報', 'Interior Design AI Platform: space renders, style previews and auto proposal decks') },
   thumbnail: { src: '/assets/cases/interior.webp', w: 1100, h: 490 },
   gallery: [
     { src: '/assets/cases/interior.webp', fallback: '/assets/works/work-interior.png', w: 1100, h: 490, alt: t('室內設計 AI 整合平台畫面:空間渲染、風格模擬與自動提案簡報', 'Interior Design AI Platform: space renders, style previews and auto proposal decks') },
     { src: '/assets/cases/interior-g1.webp', fallback: '/assets/works/work-interior.png', w: 820, h: 869, alt: t('室內設計 AI 整合平台——空間渲染與風格模擬介面', 'Interior Design AI Platform — space render and style preview UI') },
     { src: '/assets/cases/interior-g2.webp', fallback: '/assets/works/work-interior.png', w: 820, h: 747, alt: t('室內設計 AI 整合平台——設計提案生成介面', 'Interior Design AI Platform — proposal generation UI') },
     { src: '/assets/cases/interior-g3.webp', fallback: '/assets/works/work-interior.png', w: 820, h: 869, alt: t('室內設計 AI 整合平台——簡報輸出與專案畫面', 'Interior Design AI Platform — deck export and project view') }
 ] },
 { slug: 'realestate', name: t('房仲 AI 助手', 'Real-Estate AI Assistant'), industry: t('房仲不動產', 'Real estate'), type: t('AI 系統', 'AI system'), sourcePage: 'p27', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: '/assets/cases/realestate.webp', fallback: '/assets/works/work-realestate.png', w: 1100, h: 490, alt: t('房仲 AI 助手畫面:串接 LINE 官方帳號自動回物件、排預約帶看', 'Real-Estate AI Assistant: LINE OA integration, auto listing replies and viewing bookings') },
   thumbnail: { src: '/assets/cases/realestate.webp', w: 1100, h: 490 },
   gallery: [
     { src: '/assets/cases/realestate.webp', fallback: '/assets/works/work-realestate.png', w: 1100, h: 490, alt: t('房仲 AI 助手畫面:串接 LINE 官方帳號自動回物件、排預約帶看', 'Real-Estate AI Assistant: LINE OA integration, auto listing replies and viewing bookings') },
     { src: '/assets/cases/realestate-g1.webp', fallback: '/assets/works/work-realestate.png', w: 820, h: 869, alt: t('房仲 AI 助手——LINE 物件自動回覆對話', 'Real-Estate AI Assistant — auto listing replies in LINE') },
     { src: '/assets/cases/realestate-g2.webp', fallback: '/assets/works/work-realestate.png', w: 820, h: 747, alt: t('房仲 AI 助手——預約帶看排程介面', 'Real-Estate AI Assistant — viewing booking scheduler') },
     { src: '/assets/cases/realestate-g3.webp', fallback: '/assets/works/work-realestate.png', w: 820, h: 869, alt: t('房仲 AI 助手——物件與名單管理畫面', 'Real-Estate AI Assistant — listing and lead management') }
 ] },
];

export const WORKS_MEDIA = [
 { slug: 'xintu', name: t('心途', 'Xintu'), d: t('LINE 定課任務管理工具', 'LINE course-task manager'), type: t('營運工具', 'Ops tool'), industry: t('教育培訓', 'Education'), url: null, sourcePage: 'p28', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: '/assets/cases/xintu.webp', fallback: '/assets/cases/xintu.jpg', w: 1100, h: 490, alt: t('心途——LINE 定課任務管理工具(實際產品畫面)', 'Xintu — LINE course-task manager (product screenshot)') },
   thumbnail: { src: '/assets/cases/xintu.webp', w: 1100, h: 490 },
   gallery: [ { src: '/assets/cases/xintu.webp', fallback: '/assets/cases/xintu.jpg', w: 1100, h: 490, alt: t('心途——LINE 定課任務管理工具(實際產品畫面)', 'Xintu — LINE course-task manager (product screenshot)') } ] },
 { slug: 'tables', name: t('AI 排桌排房', 'AI Table & Room Planner'), d: t('自動排組桌、排房工具', 'Auto table and room assignment'), type: t('營運工具', 'Ops tool'), industry: t('婚禮婚慶', 'Weddings'), url: null, sourcePage: 'p29', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: '/assets/cases/tables.webp', fallback: '/assets/works/work-tables.png', w: 1100, h: 490, alt: t('AI 排桌排房——自動排組桌、排房工具(實際產品畫面)', 'AI Table & Room Planner — auto table and room assignment (product screenshot)') },
   thumbnail: { src: '/assets/cases/tables.webp', w: 1100, h: 490 },
   gallery: [ { src: '/assets/cases/tables.webp', fallback: '/assets/works/work-tables.png', w: 1100, h: 490, alt: t('AI 排桌排房——自動排組桌、排房工具(實際產品畫面)', 'AI Table & Room Planner — auto table and room assignment (product screenshot)') } ] },
 { slug: 'qiancheng', name: t('牽成', 'Chian-Sing'), d: t('任務回報/團隊管理系統', 'Task reporting & team management'), type: t('營運工具', 'Ops tool'), industry: t('團隊營運', 'Team operations'), url: null, sourcePage: 'p30', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: '/assets/cases/qiancheng.webp', fallback: '/assets/works/work-tasks.png', w: 1100, h: 490, alt: t('牽成——任務回報/團隊管理系統(實際產品畫面)', 'Chian-Sing — task reporting & team management (product screenshot)') },
   thumbnail: { src: '/assets/cases/qiancheng.webp', w: 1100, h: 490 },
   gallery: [ { src: '/assets/cases/qiancheng.webp', fallback: '/assets/works/work-tasks.png', w: 1100, h: 490, alt: t('牽成——任務回報/團隊管理系統(實際產品畫面)', 'Chian-Sing — task reporting & team management (product screenshot)') } ] },
 { slug: 'groupbuy', name: t('團購通', 'GroupBuy Go'), d: t('電商系統,串接 LINE 官方帳號', 'Commerce with LINE OA integration'), type: t('客製平台', 'Custom platform'), industry: t('團購電商', 'Group-buy commerce'), url: null, sourcePage: 'p31', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: '/assets/cases/groupbuy.webp', fallback: '/assets/works/work-groupbuy.png', w: 1100, h: 490, alt: t('團購通——電商系統,串接 LINE 官方帳號(實際產品畫面)', 'GroupBuy Go — commerce with LINE OA integration (product screenshot)') },
   thumbnail: { src: '/assets/cases/groupbuy.webp', w: 1100, h: 490 },
   gallery: [ { src: '/assets/cases/groupbuy.webp', fallback: '/assets/works/work-groupbuy.png', w: 1100, h: 490, alt: t('團購通——電商系統,串接 LINE 官方帳號(實際產品畫面)', 'GroupBuy Go — commerce with LINE OA integration (product screenshot)') } ] },
 { slug: 'hungmen', name: 'Hungmen Voice', d: t('聲音檢測自我狀態報告', 'Voice-based self-state reports'), type: t('AI 系統', 'AI system'), industry: t('健康檢測', 'Health screening'), url: null, sourcePage: 'p32', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: '/assets/cases/hungmen.webp', fallback: '/assets/cases/hungmen.jpg', w: 1100, h: 490, alt: t('Hungmen Voice——聲音檢測自我狀態報告(實際產品畫面)', 'Hungmen Voice — voice-based self-state reports (product screenshot)') },
   thumbnail: { src: '/assets/cases/hungmen.webp', w: 1100, h: 490 },
   gallery: [ { src: '/assets/cases/hungmen.webp', fallback: '/assets/cases/hungmen.jpg', w: 1100, h: 490, alt: t('Hungmen Voice——聲音檢測自我狀態報告(實際產品畫面)', 'Hungmen Voice — voice-based self-state reports (product screenshot)') } ] },
 { slug: 'shennong', name: t('AI 神農氏', 'AI Shennong'), d: t('保健品配方健檢與開發評估', 'Supplement formula checks and R&D review'), type: t('AI 系統', 'AI system'), industry: t('保健食品', 'Supplements'), url: null, sourcePage: 'p33', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: '/assets/cases/shennong.webp', fallback: '/assets/cases/shennong.jpg', w: 1100, h: 490, alt: t('AI 神農氏——保健品配方健檢與開發評估(實際產品畫面)', 'AI Shennong — supplement formula checks and R&D review (product screenshot)') },
   thumbnail: { src: '/assets/cases/shennong.webp', w: 1100, h: 490 },
   gallery: [ { src: '/assets/cases/shennong.webp', fallback: '/assets/cases/shennong.jpg', w: 1100, h: 490, alt: t('AI 神農氏——保健品配方健檢與開發評估(實際產品畫面)', 'AI Shennong — supplement formula checks and R&D review (product screenshot)') } ] },
 { slug: 'autodraft', name: t('AutoDraft 台灣 AI 補助王', 'AutoDraft Grant Writer'), d: t('補助計畫書 AI 搜尋、分析與撰寫', 'AI search, analysis and drafting for grant proposals'), type: t('AI 系統', 'AI system'), industry: t('企業服務', 'Business services'), url: 'https://autodraft-mvp.vercel.app/', sourcePage: 'p35', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: '/assets/cases/autodraft.webp', fallback: '/assets/cases/autodraft.jpg', w: 1100, h: 433, alt: t('AutoDraft 台灣 AI 補助王——補助計畫書 AI 搜尋、分析與撰寫(實際產品畫面)', 'AutoDraft Grant Writer — AI search, analysis and drafting for grant proposals (product screenshot)') },
   thumbnail: { src: '/assets/cases/autodraft.webp', w: 1100, h: 433 },
   gallery: [ { src: '/assets/cases/autodraft.webp', fallback: '/assets/cases/autodraft.jpg', w: 1100, h: 433, alt: t('AutoDraft 台灣 AI 補助王——補助計畫書 AI 搜尋、分析與撰寫(實際產品畫面)', 'AutoDraft Grant Writer — AI search, analysis and drafting for grant proposals (product screenshot)') } ] },
 { slug: 'pounds', name: 'Pounds Network', d: t('服務業會員忠誠度與獎勵平台', 'Loyalty and rewards platform for services'), type: t('AI 系統', 'AI system'), industry: t('服務業', 'Services'), url: 'https://www.pounds.network/en', sourcePage: 'p36', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: '/assets/cases/pounds.webp', fallback: '/assets/cases/pounds.jpg', w: 1100, h: 433, alt: t('Pounds Network——服務業會員忠誠度與獎勵平台(實際產品畫面)', 'Pounds Network — loyalty and rewards platform for services (product screenshot)') },
   thumbnail: { src: '/assets/cases/pounds.webp', w: 1100, h: 433 },
   gallery: [ { src: '/assets/cases/pounds.webp', fallback: '/assets/cases/pounds.jpg', w: 1100, h: 433, alt: t('Pounds Network——服務業會員忠誠度與獎勵平台(實際產品畫面)', 'Pounds Network — loyalty and rewards platform for services (product screenshot)') } ] },
 { slug: 'linesummary', name: t('AI LINE 群組摘要', 'AI LINE Group Digest'), d: t('LINE 群組對話自動總結', 'Auto-summary for LINE group chats'), type: t('營運工具', 'Ops tool'), industry: t('團隊營運', 'Team operations'), url: 'https://line-requirement-bot.vercel.app/', sourcePage: 'p37', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: '/assets/cases/linesummary.webp', fallback: '/assets/works/work-linesummary.png', w: 1100, h: 490, alt: t('AI LINE 群組摘要——LINE 群組對話自動總結(實際產品畫面)', 'AI LINE Group Digest — auto-summary for LINE group chats (product screenshot)') },
   thumbnail: { src: '/assets/cases/linesummary.webp', w: 1100, h: 490 },
   gallery: [ { src: '/assets/cases/linesummary.webp', fallback: '/assets/works/work-linesummary.png', w: 1100, h: 490, alt: t('AI LINE 群組摘要——LINE 群組對話自動總結(實際產品畫面)', 'AI LINE Group Digest — auto-summary for LINE group chats (product screenshot)') } ] },
 { slug: 'ludongbin', name: t('AI 呂洞賓', 'AI Lü Dongbin'), d: t('算命/解籤系統', 'Fortune-telling and lot-reading system'), type: t('AI 系統', 'AI system'), industry: t('命理文化', 'Fortune-telling'), url: null, sourcePage: 'p38', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: '/assets/cases/ludongbin.webp', fallback: '/assets/cases/ludongbin.jpg', w: 1100, h: 490, alt: t('AI 呂洞賓——算命/解籤系統(實際產品畫面)', 'AI Lü Dongbin — fortune-telling and lot-reading system (product screenshot)') },
   thumbnail: { src: '/assets/cases/ludongbin.webp', w: 1100, h: 490 },
   gallery: [ { src: '/assets/cases/ludongbin.webp', fallback: '/assets/cases/ludongbin.jpg', w: 1100, h: 490, alt: t('AI 呂洞賓——算命/解籤系統(實際產品畫面)', 'AI Lü Dongbin — fortune-telling and lot-reading system (product screenshot)') } ] },
 { slug: 'nivora', name: 'Nivora AI', d: t('AI Agent 虛擬辦公室', 'AI-agent virtual office'), type: t('AI 系統', 'AI system'), industry: t('企業服務', 'Business services'), url: null, sourcePage: 'p39', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: '/assets/cases/nivora.webp', fallback: '/assets/cases/nivora.jpg', w: 1100, h: 490, alt: t('Nivora AI——AI Agent 虛擬辦公室(實際產品畫面)', 'Nivora AI — AI-agent virtual office (product screenshot)') },
   thumbnail: { src: '/assets/cases/nivora.webp', w: 1100, h: 490 },
   gallery: [ { src: '/assets/cases/nivora.webp', fallback: '/assets/cases/nivora.jpg', w: 1100, h: 490, alt: t('Nivora AI——AI Agent 虛擬辦公室(實際產品畫面)', 'Nivora AI — AI-agent virtual office (product screenshot)') } ] },
 { slug: 'expo', name: t('嘉義市世博會官網', 'Chiayi Expo Official Site'), d: t('市府級大型活動網站,如期交付上線', 'City-level event site, shipped on schedule'), type: t('品牌網站', 'Brand site'), industry: t('政府活動', 'Government events'), url: null, sourcePage: 'p49', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: '/assets/cases/expo.webp', fallback: '/assets/works/work-expo.png', w: 1100, h: 490, alt: t('嘉義市世博會官網——市府級大型活動網站,如期交付上線(實際產品畫面)', 'Chiayi Expo Official Site — city-level event site, shipped on schedule (product screenshot)') },
   thumbnail: { src: '/assets/cases/expo.webp', w: 1100, h: 490 },
   gallery: [ { src: '/assets/cases/expo.webp', fallback: '/assets/works/work-expo.png', w: 1100, h: 490, alt: t('嘉義市世博會官網——市府級大型活動網站,如期交付上線(實際產品畫面)', 'Chiayi Expo Official Site — city-level event site, shipped on schedule (product screenshot)') } ] },
 { slug: 'rouzhi', name: t('ROUZHI 顏植髮泥', 'ROUZHI'), d: t('品牌官網', 'Brand site'), type: t('品牌網站', 'Brand site'), industry: t('美妝保養', 'Beauty & skincare'), url: 'https://rouzhi.tw/', sourcePage: 'p42', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: '/assets/cases/rouzhi.webp', fallback: '/assets/cases/rouzhi.jpg', w: 1100, h: 490, alt: t('ROUZHI 顏植髮泥——品牌官網(實際產品畫面)', 'ROUZHI — brand site (product screenshot)') },
   thumbnail: { src: '/assets/cases/rouzhi.webp', w: 1100, h: 490 },
   gallery: [ { src: '/assets/cases/rouzhi.webp', fallback: '/assets/cases/rouzhi.jpg', w: 1100, h: 490, alt: t('ROUZHI 顏植髮泥——品牌官網(實際產品畫面)', 'ROUZHI — brand site (product screenshot)') } ] },
 { slug: 'ouros', name: 'OUROS', d: t('AI 課程網頁設計', 'AI course site design'), type: t('品牌網站', 'Brand site'), industry: t('教育培訓', 'Education'), url: 'https://www.ouros.tw/', sourcePage: 'p43', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: '/assets/cases/ouros.webp', fallback: '/assets/cases/ouros.jpg', w: 1100, h: 490, alt: t('OUROS——AI 課程網頁設計(實際產品畫面)', 'OUROS — AI course site design (product screenshot)') },
   thumbnail: { src: '/assets/cases/ouros.webp', w: 1100, h: 490 },
   gallery: [ { src: '/assets/cases/ouros.webp', fallback: '/assets/cases/ouros.jpg', w: 1100, h: 490, alt: t('OUROS——AI 課程網頁設計(實際產品畫面)', 'OUROS — AI course site design (product screenshot)') } ] },
 { slug: 'doiiin', name: t('DOIIIN ESG 平台', 'DOIIIN ESG Platform'), d: t('網頁設計顧問暨製作', 'Web design consulting and build'), type: t('品牌網站', 'Brand site'), industry: t('ESG 永續', 'ESG'), url: 'https://v0-esg-media-platform.vercel.app/', sourcePage: 'p45', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: '/assets/cases/doiiin.webp', fallback: '/assets/cases/doiiin.jpg', w: 1100, h: 490, alt: t('DOIIIN ESG 平台——網頁設計顧問暨製作(實際產品畫面)', 'DOIIIN ESG Platform — web design consulting and build (product screenshot)') },
   thumbnail: { src: '/assets/cases/doiiin.webp', w: 1100, h: 490 },
   gallery: [ { src: '/assets/cases/doiiin.webp', fallback: '/assets/cases/doiiin.jpg', w: 1100, h: 490, alt: t('DOIIIN ESG 平台——網頁設計顧問暨製作(實際產品畫面)', 'DOIIIN ESG Platform — web design consulting and build (product screenshot)') } ] },
 { slug: 'sparkspace', name: t('SparkSpace 倉儲監控', 'SparkSpace Warehouse Monitor'), d: t('倉儲監控系統', 'Warehouse monitoring system'), type: t('客製平台', 'Custom platform'), industry: t('物流倉儲', 'Warehousing & logistics'), url: 'https://www.sparkspace.com.tw/', sourcePage: 'p46', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: '/assets/cases/sparkspace.webp', fallback: '/assets/works/work-warehouse.png', w: 1100, h: 490, alt: t('SparkSpace 倉儲監控——倉儲監控系統(實際產品畫面)', 'SparkSpace Warehouse Monitor — warehouse monitoring system (product screenshot)') },
   thumbnail: { src: '/assets/cases/sparkspace.webp', w: 1100, h: 490 },
   gallery: [ { src: '/assets/cases/sparkspace.webp', fallback: '/assets/works/work-warehouse.png', w: 1100, h: 490, alt: t('SparkSpace 倉儲監控——倉儲監控系統(實際產品畫面)', 'SparkSpace Warehouse Monitor — warehouse monitoring system (product screenshot)') } ] },
 { slug: 'palace', name: t('宮廷命理研究院', 'Palace Numerology Institute'), d: t('算名系統與課程', 'Name-reading system and courses'), type: t('客製平台', 'Custom platform'), industry: t('命理文化', 'Fortune-telling'), url: 'https://palace-virid-nine.vercel.app/', sourcePage: 'p44', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: '/assets/cases/palace.webp', fallback: '/assets/cases/palace.jpg', w: 1100, h: 490, alt: t('宮廷命理研究院——算名系統與課程(實際產品畫面)', 'Palace Numerology Institute — name-reading system and courses (product screenshot)') },
   thumbnail: { src: '/assets/cases/palace.webp', w: 1100, h: 490 },
   gallery: [ { src: '/assets/cases/palace.webp', fallback: '/assets/cases/palace.jpg', w: 1100, h: 490, alt: t('宮廷命理研究院——算名系統與課程(實際產品畫面)', 'Palace Numerology Institute — name-reading system and courses (product screenshot)') } ] },
 { slug: 'innerweather', name: 'Inner Weather', d: t('VJ 用視覺軟體', 'Visual software for VJs'), type: t('客製平台', 'Custom platform'), industry: t('演出視覺', 'Stage visuals'), url: 'https://love-hazel-two.vercel.app/', sourcePage: 'p41', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: '/assets/cases/innerweather.webp', fallback: '/assets/cases/innerweather.jpg', w: 1100, h: 490, alt: t('Inner Weather——VJ 用視覺軟體(實際產品畫面)', 'Inner Weather — visual software for VJs (product screenshot)') },
   thumbnail: { src: '/assets/cases/innerweather.webp', w: 1100, h: 490 },
   gallery: [ { src: '/assets/cases/innerweather.webp', fallback: '/assets/cases/innerweather.jpg', w: 1100, h: 490, alt: t('Inner Weather——VJ 用視覺軟體(實際產品畫面)', 'Inner Weather — visual software for VJs (product screenshot)') } ] },
 { slug: 'asml', name: 'ASML', d: t('品牌官網', 'Brand site'), type: t('品牌網站', 'Brand site'), industry: t('科技製造', 'Tech manufacturing'), url: null, sourcePage: 'p47', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: '/assets/cases/asml.webp', fallback: '/assets/cases/asml.jpg', w: 1100, h: 490, alt: t('ASML——品牌官網(實際產品畫面)', 'ASML — brand site (product screenshot)') },
   thumbnail: { src: '/assets/cases/asml.webp', w: 1100, h: 490 },
   gallery: [ { src: '/assets/cases/asml.webp', fallback: '/assets/cases/asml.jpg', w: 1100, h: 490, alt: t('ASML——品牌官網(實際產品畫面)', 'ASML — brand site (product screenshot)') } ] },
 { slug: 'labubu', name: t('拉步步', 'Labubu'), d: t('活動售票系統', 'Event ticketing system'), type: t('客製平台', 'Custom platform'), industry: t('活動售票', 'Event ticketing'), url: null, sourcePage: 'p48', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: '/assets/cases/labubu.webp', fallback: '/assets/cases/labubu.jpg', w: 1100, h: 490, alt: t('拉步步——活動售票系統(實際產品畫面)', 'Labubu — event ticketing system (product screenshot)') },
   thumbnail: { src: '/assets/cases/labubu.webp', w: 1100, h: 490 },
   gallery: [ { src: '/assets/cases/labubu.webp', fallback: '/assets/cases/labubu.jpg', w: 1100, h: 490, alt: t('拉步步——活動售票系統(實際產品畫面)', 'Labubu — event ticketing system (product screenshot)') } ] },
 { slug: 'greenpark', name: t('台中綠園', 'Taichung Green Garden'), d: t('圖庫房系統', 'Image library system'), type: t('客製平台', 'Custom platform'), industry: t('不動產', 'Real estate'), url: null, sourcePage: 'p50', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: '/assets/cases/greenpark.webp', fallback: '/assets/cases/greenpark.jpg', w: 1100, h: 490, alt: t('台中綠園——圖庫房系統(實際產品畫面)', 'Taichung Green Garden — image library system (product screenshot)') },
   thumbnail: { src: '/assets/cases/greenpark.webp', w: 1100, h: 490 },
   gallery: [ { src: '/assets/cases/greenpark.webp', fallback: '/assets/cases/greenpark.jpg', w: 1100, h: 490, alt: t('台中綠園——圖庫房系統(實際產品畫面)', 'Taichung Green Garden — image library system (product screenshot)') } ] },
 { slug: 'community', name: t('社區管理 APP', 'Community Management App'), d: t('社區管理 APP 與後台', 'Community app with back office'), type: t('客製平台', 'Custom platform'), industry: t('社區管理', 'Community management'), url: null, sourcePage: 'p51', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: '/assets/cases/community.webp', fallback: '/assets/works/work-community.png', w: 1100, h: 490, alt: t('社區管理 APP——社區管理 APP 與後台(實際產品畫面)', 'Community Management App — community app with back office (product screenshot)') },
   thumbnail: { src: '/assets/cases/community.webp', w: 1100, h: 490 },
   gallery: [ { src: '/assets/cases/community.webp', fallback: '/assets/works/work-community.png', w: 1100, h: 490, alt: t('社區管理 APP——社區管理 APP 與後台(實際產品畫面)', 'Community Management App — community app with back office (product screenshot)') } ] },
 { slug: 'rental', name: t('租屋管理平台', 'Rental Management Platform'), d: t('租屋與物件管理', 'Rentals and listings management'), type: t('客製平台', 'Custom platform'), industry: t('不動產', 'Real estate'), url: null, sourcePage: 'p52', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: '/assets/cases/rental.webp', fallback: '/assets/cases/rental.jpg', w: 1100, h: 490, alt: t('租屋管理平台——租屋與物件管理(實際產品畫面)', 'Rental Management Platform — rentals and listings management (product screenshot)') },
   thumbnail: { src: '/assets/cases/rental.webp', w: 1100, h: 490 },
   gallery: [ { src: '/assets/cases/rental.webp', fallback: '/assets/cases/rental.jpg', w: 1100, h: 490, alt: t('租屋管理平台——租屋與物件管理(實際產品畫面)', 'Rental Management Platform — rentals and listings management (product screenshot)') } ] },
 { slug: 'forum', name: t('顏博士論壇', 'Dr. Yan Forum'), d: t('論壇網站', 'Forum site'), type: t('品牌網站', 'Brand site'), industry: t('醫療知識', 'Medical knowledge'), url: null, sourcePage: 'p53', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: '/assets/cases/forum.webp', fallback: '/assets/cases/forum.jpg', w: 1100, h: 490, alt: t('顏博士論壇——論壇網站(實際產品畫面)', 'Dr. Yan Forum — forum site (product screenshot)') },
   thumbnail: { src: '/assets/cases/forum.webp', w: 1100, h: 490 },
   gallery: [ { src: '/assets/cases/forum.webp', fallback: '/assets/cases/forum.jpg', w: 1100, h: 490, alt: t('顏博士論壇——論壇網站(實際產品畫面)', 'Dr. Yan Forum — forum site (product screenshot)') } ] },
];

// 尚無公開截圖 → 不得以案例卡公開,列為「可開發能力」
export const CAPABILITIES_NO_MEDIA = [
  { name: t('美業 AI 體驗系統', 'Beauty AI Experience'), d: t('髮色試換、妝容模擬、美甲預覽(截圖素材待補,暫不公開為案例卡)', 'Hair color try-on, makeup previews and nail previews (screenshots pending, not yet published as a case card)') }
];
