// 自動產生:案例素材資料模型(來源:Sales Kit p24–p53 實際產品/網站畫面,經裁切去簡報框)
// 欄位:slug/name/industry/type/url/sourcePage/mediaType/focalPoint/cover{src,fallback,w,h,alt}/thumbnail/gallery[]
export const FEATURED_MEDIA = [
 { slug: 'wedding', name: '婚禮產業 AI 大禮包', industry: '婚禮婚慶', type: 'AI 系統', sourcePage: 'p24', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: 'assets/cases/wedding.webp', fallback: 'assets/works/work-wedding.png', w: 1100, h: 490, alt: '婚禮產業 AI 大禮包系統畫面:婚紗試穿模擬、社群發文中心與客戶續談 CRM' },
   thumbnail: { src: 'assets/cases/wedding.webp', w: 1100, h: 490 },
   gallery: [
     { src: 'assets/cases/wedding.webp', fallback: 'assets/works/work-wedding.png', w: 1100, h: 490, alt: '婚禮產業 AI 大禮包系統畫面:婚紗試穿模擬、社群發文中心與客戶續談 CRM' },
     { src: 'assets/cases/wedding-g1.webp', fallback: 'assets/works/work-wedding.png', w: 820, h: 869, alt: '婚禮產業 AI 大禮包——婚紗試穿與試妝模擬介面' },
     { src: 'assets/cases/wedding-g2.webp', fallback: 'assets/works/work-wedding.png', w: 820, h: 747, alt: '婚禮產業 AI 大禮包——社群影片與發文中心介面' },
     { src: 'assets/cases/wedding-g3.webp', fallback: 'assets/works/work-wedding.png', w: 820, h: 869, alt: '婚禮產業 AI 大禮包——客戶續談 CRM 與名單畫面' }
 ] },
 { slug: 'interior', name: '室內設計 AI 整合平台', industry: '室內設計裝修', type: 'AI 系統', sourcePage: 'p25', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: 'assets/cases/interior.webp', fallback: 'assets/works/work-interior.png', w: 1100, h: 490, alt: '室內設計 AI 整合平台畫面:空間渲染、風格模擬與自動提案簡報' },
   thumbnail: { src: 'assets/cases/interior.webp', w: 1100, h: 490 },
   gallery: [
     { src: 'assets/cases/interior.webp', fallback: 'assets/works/work-interior.png', w: 1100, h: 490, alt: '室內設計 AI 整合平台畫面:空間渲染、風格模擬與自動提案簡報' },
     { src: 'assets/cases/interior-g1.webp', fallback: 'assets/works/work-interior.png', w: 820, h: 869, alt: '室內設計 AI 整合平台——空間渲染與風格模擬介面' },
     { src: 'assets/cases/interior-g2.webp', fallback: 'assets/works/work-interior.png', w: 820, h: 747, alt: '室內設計 AI 整合平台——設計提案生成介面' },
     { src: 'assets/cases/interior-g3.webp', fallback: 'assets/works/work-interior.png', w: 820, h: 869, alt: '室內設計 AI 整合平台——簡報輸出與專案畫面' }
 ] },
 { slug: 'social', name: 'AI 社群自動經營系統', industry: '社群經營', type: 'AI 系統', sourcePage: 'p26', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: 'assets/cases/social.webp', fallback: 'assets/works/work-social.png', w: 1100, h: 490, alt: 'AI 社群自動經營系統畫面:依產業自動產文與排程發布' },
   thumbnail: { src: 'assets/cases/social.webp', w: 1100, h: 490 },
   gallery: [
     { src: 'assets/cases/social.webp', fallback: 'assets/works/work-social.png', w: 1100, h: 490, alt: 'AI 社群自動經營系統畫面:依產業自動產文與排程發布' },
     { src: 'assets/cases/social-g1.webp', fallback: 'assets/works/work-social.png', w: 820, h: 869, alt: 'AI 社群自動經營系統——AI 產文編輯介面' },
     { src: 'assets/cases/social-g2.webp', fallback: 'assets/works/work-social.png', w: 820, h: 747, alt: 'AI 社群自動經營系統——排程發布中心' },
     { src: 'assets/cases/social-g3.webp', fallback: 'assets/works/work-social.png', w: 820, h: 869, alt: 'AI 社群自動經營系統——貼文成效清單畫面' }
 ] },
 { slug: 'realestate', name: '房仲 AI 助手', industry: '房仲不動產', type: 'AI 系統', sourcePage: 'p27', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: 'assets/cases/realestate.webp', fallback: 'assets/works/work-realestate.png', w: 1100, h: 490, alt: '房仲 AI 助手畫面:串接 LINE 官方帳號自動回物件、排預約帶看' },
   thumbnail: { src: 'assets/cases/realestate.webp', w: 1100, h: 490 },
   gallery: [
     { src: 'assets/cases/realestate.webp', fallback: 'assets/works/work-realestate.png', w: 1100, h: 490, alt: '房仲 AI 助手畫面:串接 LINE 官方帳號自動回物件、排預約帶看' },
     { src: 'assets/cases/realestate-g1.webp', fallback: 'assets/works/work-realestate.png', w: 820, h: 869, alt: '房仲 AI 助手——LINE 物件自動回覆對話' },
     { src: 'assets/cases/realestate-g2.webp', fallback: 'assets/works/work-realestate.png', w: 820, h: 747, alt: '房仲 AI 助手——預約帶看排程介面' },
     { src: 'assets/cases/realestate-g3.webp', fallback: 'assets/works/work-realestate.png', w: 820, h: 869, alt: '房仲 AI 助手——物件與名單管理畫面' }
 ] },
];

export const WORKS_MEDIA = [
 { slug: 'xintu', name: '心途', d: 'LINE 定課任務管理工具', type: '營運工具', industry: '教育培訓', url: null, sourcePage: 'p28', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: 'assets/cases/xintu.webp', fallback: 'assets/cases/xintu.jpg', w: 1100, h: 490, alt: '心途——LINE 定課任務管理工具(實際產品畫面)' },
   thumbnail: { src: 'assets/cases/xintu.webp', w: 1100, h: 490 },
   gallery: [ { src: 'assets/cases/xintu.webp', fallback: 'assets/cases/xintu.jpg', w: 1100, h: 490, alt: '心途——LINE 定課任務管理工具(實際產品畫面)' } ] },
 { slug: 'tables', name: 'AI 排桌排房', d: '自動排組桌、排房工具', type: '營運工具', industry: '婚禮婚慶', url: null, sourcePage: 'p29', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: 'assets/cases/tables.webp', fallback: 'assets/works/work-tables.png', w: 1100, h: 490, alt: 'AI 排桌排房——自動排組桌、排房工具(實際產品畫面)' },
   thumbnail: { src: 'assets/cases/tables.webp', w: 1100, h: 490 },
   gallery: [ { src: 'assets/cases/tables.webp', fallback: 'assets/works/work-tables.png', w: 1100, h: 490, alt: 'AI 排桌排房——自動排組桌、排房工具(實際產品畫面)' } ] },
 { slug: 'qiancheng', name: '牽成', d: '任務回報/團隊管理系統', type: '營運工具', industry: '團隊營運', url: null, sourcePage: 'p30', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: 'assets/cases/qiancheng.webp', fallback: 'assets/works/work-tasks.png', w: 1100, h: 490, alt: '牽成——任務回報/團隊管理系統(實際產品畫面)' },
   thumbnail: { src: 'assets/cases/qiancheng.webp', w: 1100, h: 490 },
   gallery: [ { src: 'assets/cases/qiancheng.webp', fallback: 'assets/works/work-tasks.png', w: 1100, h: 490, alt: '牽成——任務回報/團隊管理系統(實際產品畫面)' } ] },
 { slug: 'groupbuy', name: '團購通', d: '電商系統,串接 LINE 官方帳號', type: '客製平台', industry: '團購電商', url: null, sourcePage: 'p31', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: 'assets/cases/groupbuy.webp', fallback: 'assets/works/work-groupbuy.png', w: 1100, h: 490, alt: '團購通——電商系統,串接 LINE 官方帳號(實際產品畫面)' },
   thumbnail: { src: 'assets/cases/groupbuy.webp', w: 1100, h: 490 },
   gallery: [ { src: 'assets/cases/groupbuy.webp', fallback: 'assets/works/work-groupbuy.png', w: 1100, h: 490, alt: '團購通——電商系統,串接 LINE 官方帳號(實際產品畫面)' } ] },
 { slug: 'hungmen', name: 'Hungmen Voice', d: '聲音檢測自我狀態報告', type: 'AI 系統', industry: '健康檢測', url: null, sourcePage: 'p32', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: 'assets/cases/hungmen.webp', fallback: 'assets/cases/hungmen.jpg', w: 1100, h: 490, alt: 'Hungmen Voice——聲音檢測自我狀態報告(實際產品畫面)' },
   thumbnail: { src: 'assets/cases/hungmen.webp', w: 1100, h: 490 },
   gallery: [ { src: 'assets/cases/hungmen.webp', fallback: 'assets/cases/hungmen.jpg', w: 1100, h: 490, alt: 'Hungmen Voice——聲音檢測自我狀態報告(實際產品畫面)' } ] },
 { slug: 'shennong', name: 'AI 神農氏', d: '保健品配方健檢與開發評估', type: 'AI 系統', industry: '保健食品', url: null, sourcePage: 'p33', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: 'assets/cases/shennong.webp', fallback: 'assets/cases/shennong.jpg', w: 1100, h: 490, alt: 'AI 神農氏——保健品配方健檢與開發評估(實際產品畫面)' },
   thumbnail: { src: 'assets/cases/shennong.webp', w: 1100, h: 490 },
   gallery: [ { src: 'assets/cases/shennong.webp', fallback: 'assets/cases/shennong.jpg', w: 1100, h: 490, alt: 'AI 神農氏——保健品配方健檢與開發評估(實際產品畫面)' } ] },
 { slug: 'autodraft', name: 'AutoDraft 台灣 AI 補助王', d: '補助計畫書 AI 搜尋、分析與撰寫', type: 'AI 系統', industry: '企業服務', url: 'https://autodraft-mvp.vercel.app/', sourcePage: 'p35', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: 'assets/cases/autodraft.webp', fallback: 'assets/cases/autodraft.jpg', w: 1100, h: 433, alt: 'AutoDraft 台灣 AI 補助王——補助計畫書 AI 搜尋、分析與撰寫(實際產品畫面)' },
   thumbnail: { src: 'assets/cases/autodraft.webp', w: 1100, h: 433 },
   gallery: [ { src: 'assets/cases/autodraft.webp', fallback: 'assets/cases/autodraft.jpg', w: 1100, h: 433, alt: 'AutoDraft 台灣 AI 補助王——補助計畫書 AI 搜尋、分析與撰寫(實際產品畫面)' } ] },
 { slug: 'pounds', name: 'Pounds Network', d: '服務業會員忠誠度與獎勵平台', type: 'AI 系統', industry: '服務業', url: 'https://www.pounds.network/en', sourcePage: 'p36', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: 'assets/cases/pounds.webp', fallback: 'assets/cases/pounds.jpg', w: 1100, h: 433, alt: 'Pounds Network——服務業會員忠誠度與獎勵平台(實際產品畫面)' },
   thumbnail: { src: 'assets/cases/pounds.webp', w: 1100, h: 433 },
   gallery: [ { src: 'assets/cases/pounds.webp', fallback: 'assets/cases/pounds.jpg', w: 1100, h: 433, alt: 'Pounds Network——服務業會員忠誠度與獎勵平台(實際產品畫面)' } ] },
 { slug: 'linesummary', name: 'AI LINE 群組摘要', d: 'LINE 群組對話自動總結', type: '營運工具', industry: '團隊營運', url: 'https://line-requirement-bot.vercel.app/', sourcePage: 'p37', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: 'assets/cases/linesummary.webp', fallback: 'assets/works/work-linesummary.png', w: 1100, h: 490, alt: 'AI LINE 群組摘要——LINE 群組對話自動總結(實際產品畫面)' },
   thumbnail: { src: 'assets/cases/linesummary.webp', w: 1100, h: 490 },
   gallery: [ { src: 'assets/cases/linesummary.webp', fallback: 'assets/works/work-linesummary.png', w: 1100, h: 490, alt: 'AI LINE 群組摘要——LINE 群組對話自動總結(實際產品畫面)' } ] },
 { slug: 'ludongbin', name: 'AI 呂洞賓', d: '算命/解籤系統', type: 'AI 系統', industry: '命理文化', url: null, sourcePage: 'p38', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: 'assets/cases/ludongbin.webp', fallback: 'assets/cases/ludongbin.jpg', w: 1100, h: 490, alt: 'AI 呂洞賓——算命/解籤系統(實際產品畫面)' },
   thumbnail: { src: 'assets/cases/ludongbin.webp', w: 1100, h: 490 },
   gallery: [ { src: 'assets/cases/ludongbin.webp', fallback: 'assets/cases/ludongbin.jpg', w: 1100, h: 490, alt: 'AI 呂洞賓——算命/解籤系統(實際產品畫面)' } ] },
 { slug: 'nivora', name: 'Nivora AI', d: 'AI Agent 虛擬辦公室', type: 'AI 系統', industry: '企業服務', url: null, sourcePage: 'p39', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: 'assets/cases/nivora.webp', fallback: 'assets/cases/nivora.jpg', w: 1100, h: 490, alt: 'Nivora AI——AI Agent 虛擬辦公室(實際產品畫面)' },
   thumbnail: { src: 'assets/cases/nivora.webp', w: 1100, h: 490 },
   gallery: [ { src: 'assets/cases/nivora.webp', fallback: 'assets/cases/nivora.jpg', w: 1100, h: 490, alt: 'Nivora AI——AI Agent 虛擬辦公室(實際產品畫面)' } ] },
 { slug: 'expo', name: '嘉義市世博會官網', d: '市府級大型活動網站,如期交付上線', type: '品牌網站', industry: '政府活動', url: null, sourcePage: 'p49', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: 'assets/cases/expo.webp', fallback: 'assets/works/work-expo.png', w: 1100, h: 490, alt: '嘉義市世博會官網——市府級大型活動網站,如期交付上線(實際產品畫面)' },
   thumbnail: { src: 'assets/cases/expo.webp', w: 1100, h: 490 },
   gallery: [ { src: 'assets/cases/expo.webp', fallback: 'assets/works/work-expo.png', w: 1100, h: 490, alt: '嘉義市世博會官網——市府級大型活動網站,如期交付上線(實際產品畫面)' } ] },
 { slug: 'rouzhi', name: 'ROUZHI 顏植髮泥', d: '品牌官網', type: '品牌網站', industry: '美妝保養', url: 'https://rouzhi.tw/', sourcePage: 'p42', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: 'assets/cases/rouzhi.webp', fallback: 'assets/cases/rouzhi.jpg', w: 1100, h: 490, alt: 'ROUZHI 顏植髮泥——品牌官網(實際產品畫面)' },
   thumbnail: { src: 'assets/cases/rouzhi.webp', w: 1100, h: 490 },
   gallery: [ { src: 'assets/cases/rouzhi.webp', fallback: 'assets/cases/rouzhi.jpg', w: 1100, h: 490, alt: 'ROUZHI 顏植髮泥——品牌官網(實際產品畫面)' } ] },
 { slug: 'ouros', name: 'OUROS', d: 'AI 課程網頁設計', type: '品牌網站', industry: '教育培訓', url: 'https://www.ouros.tw/', sourcePage: 'p43', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: 'assets/cases/ouros.webp', fallback: 'assets/cases/ouros.jpg', w: 1100, h: 490, alt: 'OUROS——AI 課程網頁設計(實際產品畫面)' },
   thumbnail: { src: 'assets/cases/ouros.webp', w: 1100, h: 490 },
   gallery: [ { src: 'assets/cases/ouros.webp', fallback: 'assets/cases/ouros.jpg', w: 1100, h: 490, alt: 'OUROS——AI 課程網頁設計(實際產品畫面)' } ] },
 { slug: 'doiiin', name: 'DOIIIN ESG 平台', d: '網頁設計顧問暨製作', type: '品牌網站', industry: 'ESG 永續', url: 'https://v0-esg-media-platform.vercel.app/', sourcePage: 'p45', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: 'assets/cases/doiiin.webp', fallback: 'assets/cases/doiiin.jpg', w: 1100, h: 490, alt: 'DOIIIN ESG 平台——網頁設計顧問暨製作(實際產品畫面)' },
   thumbnail: { src: 'assets/cases/doiiin.webp', w: 1100, h: 490 },
   gallery: [ { src: 'assets/cases/doiiin.webp', fallback: 'assets/cases/doiiin.jpg', w: 1100, h: 490, alt: 'DOIIIN ESG 平台——網頁設計顧問暨製作(實際產品畫面)' } ] },
 { slug: 'sparkspace', name: 'SparkSpace 倉儲監控', d: '倉儲監控系統', type: '客製平台', industry: '物流倉儲', url: 'https://www.sparkspace.com.tw/', sourcePage: 'p46', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: 'assets/cases/sparkspace.webp', fallback: 'assets/works/work-warehouse.png', w: 1100, h: 490, alt: 'SparkSpace 倉儲監控——倉儲監控系統(實際產品畫面)' },
   thumbnail: { src: 'assets/cases/sparkspace.webp', w: 1100, h: 490 },
   gallery: [ { src: 'assets/cases/sparkspace.webp', fallback: 'assets/works/work-warehouse.png', w: 1100, h: 490, alt: 'SparkSpace 倉儲監控——倉儲監控系統(實際產品畫面)' } ] },
 { slug: 'palace', name: '宮廷命理研究院', d: '算名系統與課程', type: '客製平台', industry: '命理文化', url: 'https://palace-virid-nine.vercel.app/', sourcePage: 'p44', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: 'assets/cases/palace.webp', fallback: 'assets/cases/palace.jpg', w: 1100, h: 490, alt: '宮廷命理研究院——算名系統與課程(實際產品畫面)' },
   thumbnail: { src: 'assets/cases/palace.webp', w: 1100, h: 490 },
   gallery: [ { src: 'assets/cases/palace.webp', fallback: 'assets/cases/palace.jpg', w: 1100, h: 490, alt: '宮廷命理研究院——算名系統與課程(實際產品畫面)' } ] },
 { slug: 'innerweather', name: 'Inner Weather', d: 'VJ 用視覺軟體', type: '客製平台', industry: '演出視覺', url: 'https://love-hazel-two.vercel.app/', sourcePage: 'p41', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: 'assets/cases/innerweather.webp', fallback: 'assets/cases/innerweather.jpg', w: 1100, h: 490, alt: 'Inner Weather——VJ 用視覺軟體(實際產品畫面)' },
   thumbnail: { src: 'assets/cases/innerweather.webp', w: 1100, h: 490 },
   gallery: [ { src: 'assets/cases/innerweather.webp', fallback: 'assets/cases/innerweather.jpg', w: 1100, h: 490, alt: 'Inner Weather——VJ 用視覺軟體(實際產品畫面)' } ] },
 { slug: 'asml', name: 'ASML', d: '品牌官網', type: '品牌網站', industry: '科技製造', url: null, sourcePage: 'p47', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: 'assets/cases/asml.webp', fallback: 'assets/cases/asml.jpg', w: 1100, h: 490, alt: 'ASML——品牌官網(實際產品畫面)' },
   thumbnail: { src: 'assets/cases/asml.webp', w: 1100, h: 490 },
   gallery: [ { src: 'assets/cases/asml.webp', fallback: 'assets/cases/asml.jpg', w: 1100, h: 490, alt: 'ASML——品牌官網(實際產品畫面)' } ] },
 { slug: 'labubu', name: '拉步步', d: '活動售票系統', type: '客製平台', industry: '活動售票', url: null, sourcePage: 'p48', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: 'assets/cases/labubu.webp', fallback: 'assets/cases/labubu.jpg', w: 1100, h: 490, alt: '拉步步——活動售票系統(實際產品畫面)' },
   thumbnail: { src: 'assets/cases/labubu.webp', w: 1100, h: 490 },
   gallery: [ { src: 'assets/cases/labubu.webp', fallback: 'assets/cases/labubu.jpg', w: 1100, h: 490, alt: '拉步步——活動售票系統(實際產品畫面)' } ] },
 { slug: 'greenpark', name: '台中綠園', d: '圖庫房系統', type: '客製平台', industry: '不動產', url: null, sourcePage: 'p50', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: 'assets/cases/greenpark.webp', fallback: 'assets/cases/greenpark.jpg', w: 1100, h: 490, alt: '台中綠園——圖庫房系統(實際產品畫面)' },
   thumbnail: { src: 'assets/cases/greenpark.webp', w: 1100, h: 490 },
   gallery: [ { src: 'assets/cases/greenpark.webp', fallback: 'assets/cases/greenpark.jpg', w: 1100, h: 490, alt: '台中綠園——圖庫房系統(實際產品畫面)' } ] },
 { slug: 'community', name: '社區管理 APP', d: '社區管理 APP 與後台', type: '客製平台', industry: '社區管理', url: null, sourcePage: 'p51', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: 'assets/cases/community.webp', fallback: 'assets/works/work-community.png', w: 1100, h: 490, alt: '社區管理 APP——社區管理 APP 與後台(實際產品畫面)' },
   thumbnail: { src: 'assets/cases/community.webp', w: 1100, h: 490 },
   gallery: [ { src: 'assets/cases/community.webp', fallback: 'assets/works/work-community.png', w: 1100, h: 490, alt: '社區管理 APP——社區管理 APP 與後台(實際產品畫面)' } ] },
 { slug: 'rental', name: '租屋管理平台', d: '租屋與物件管理', type: '客製平台', industry: '不動產', url: null, sourcePage: 'p52', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: 'assets/cases/rental.webp', fallback: 'assets/cases/rental.jpg', w: 1100, h: 490, alt: '租屋管理平台——租屋與物件管理(實際產品畫面)' },
   thumbnail: { src: 'assets/cases/rental.webp', w: 1100, h: 490 },
   gallery: [ { src: 'assets/cases/rental.webp', fallback: 'assets/cases/rental.jpg', w: 1100, h: 490, alt: '租屋管理平台——租屋與物件管理(實際產品畫面)' } ] },
 { slug: 'forum', name: '顏博士論壇', d: '論壇網站', type: '品牌網站', industry: '醫療知識', url: null, sourcePage: 'p53', mediaType: 'screenshot', focalPoint: 'top',
   cover: { src: 'assets/cases/forum.webp', fallback: 'assets/cases/forum.jpg', w: 1100, h: 490, alt: '顏博士論壇——論壇網站(實際產品畫面)' },
   thumbnail: { src: 'assets/cases/forum.webp', w: 1100, h: 490 },
   gallery: [ { src: 'assets/cases/forum.webp', fallback: 'assets/cases/forum.jpg', w: 1100, h: 490, alt: '顏博士論壇——論壇網站(實際產品畫面)' } ] },
];

// 尚無公開截圖 → 不得以案例卡公開,列為「可開發能力」
export const CAPABILITIES_NO_MEDIA = [
  { name: '美業 AI 體驗系統', d: '髮色試換、妝容模擬、美甲預覽(截圖素材待補,暫不公開為案例卡)' }
];
